name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.9
      uses: actions/setup-java@v1
      with:
        java-version: 1.9
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
# Instrumented tests #
#    - uses: reactivecircus/android-emulator-runner@v2
#      with:
#        api-level: 23
#        target: default
#        arch: x86
#        profile: Nexus 9
#        script: ./gradlew connectedCheck --stacktrace
    ## Sign our APK##
    - name: Sign app APK
      uses: r0adkll/sign-android-release@v1
      id: sign_app
      with:
        releaseDirectory: app/build/outputs/apk/release
        alias: ${{ secrets.ANDROID_ALIAS }}
        signingKeyBase64: ${{ secrets.KEYSTORE }}
        keyStorePassword: ${{ secrets.KEY_PASSWORD }}
        keyPassword: ${{ secrets.KEY_PASSWORD }}
      env:
        # override default build-tools version (29.0.3) -- optional
        BUILD_TOOLS_VERSION: "30.0.2"

    - name: Upload our APK
      uses: actions/upload-artifact@v2.2.0
      with:
        name: Release artifact
        path: app/build/outputs/apk/release/ozonoApp-*.apk
    ## Create new release
    #- name: Create Release
    #  id: create_release
    #  uses: actions/create-release@v1
    #  env:
    #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #  with:
    #    tag_name: ${{ github.ref }}
    #    release_name: Release ${{ github.ref }}
    #    draft: false
    #    prerelease: false
