
name: Release

on:
  push:
    tags:
      - '*'
      - 'v*'

jobs:

  release:
    #name: Create Release
    #if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Release 1
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          run: |
            echo "pippo"
            echo `echo ${{ github.ref }}`
          release_name: 'release name'
          body: |
            What is new :
              - First Change
              - Second Change
          draft: false
          prerelease: false
